plugins { id 'java-library' }
java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }
dependencies {
    compileOnly 'net.fabricmc:fabric-loader:0.19.5'
    compileOnly 'net.fabricmc:sponge-mixin:0.17.4+mixin.0.8.7'
    compileOnly 'org.ow2.asm:asm:9.10.1'
    compileOnly 'org.ow2.asm:asm-tree:9.10.1'
    compileOnly 'org.ow2.asm:asm-commons:9.10.1'
}
tasks.withType(JavaCompile).configureEach { options.release = 21; options.encoding = 'UTF-8'; options.compilerArgs += ['-proc:none'] }
